[package]
name = "travelmode"
description = "travelmode command-line client"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "travelmode"
path = "src/main.rs"

[dependencies]
travelmode-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
clap.workspace = true
chrono.workspace = true
libc = "0.2"
